bump_version: null
lint: {}
nf_core_version: 3.0.1
org_path: null
repository_type: pipeline
template:
  author: Muneeb
  description: faster_metagenome_assemblies
  force: false
  is_nfcore: true
  name: metafast
  org: nf-core
  outdir: .
  skip_features: null
  version: 3.0.1
update: null
